### ISSUE TITLE
Error in processing 1p motion registration

### ISSUE THREAD

**Issue by yuanlong-o** [apasarkar/jnormcorre#11] opened 2024-07-19 08:42 UTC
Thanks for your brilliant methods and contribution. I have successfully test the motion registration in the demo 2p data. However, in my own 1p miniscope data, I catch following errors:

```python
vmap in_axes specification must be a tree prefix of the corresponding value, got specification (0, 0, None, (None, None), None) for value tree PyTreeDef((*, *, *, [*, *], *)).
ValueError: Expected tuple, got [<object object at 0x00000199F5F8A530>, <object object at 0x00000199F5F8A530>].
```
suggesting the vmap usage error. After carefully checking, I find change 
```
register_frames_to_template_1p_rigid = jit(
    vmap(_register_to_template_1p_rigid, in_axes=(0, 0, None, (None, None), None)))
```
to
```
register_frames_to_template_1p_rigid = jit(
    vmap(_register_to_template_1p_rigid, in_axes=(0, 0, None, None, None)))
```
can solve the problem. However, as I am not familiar with JAX, it would be good if you can check this problem.

Best

**Comment by apasarkar** [comment] 2024-07-19 22:05
Thank you for trying this out @yuanlong-o ! Will check this out asap -- looks like you found a bug.

**Comment by apasarkar** [comment] 2024-07-20 20:52
Hi @yuanlong-o I've looked through the code. There were no issues on my end with the original syntax. I suspect the issue is likely due to differences in jax/python versions. In any case I've tested and merged the simpler notation (essentially what you suggested), so it should work on your end in any case now. 

I'm also noting that I've updated the demo jupyter notebook -- I realized while working on this that the demo was very outdated. It's much easier to use the demo now.

I will close this issue for now; let me know if you have any other questions/suggestions and feel free to re-open this issue!

**Closed by apasarkar** 2024-07-20 20:52 UTC

**Comment by yuanlong-o** [comment] 2024-07-21 01:11
Great! Thanks for your help and active support! I really
enjoy jnormcorre for processing data and thank you so much!
